name: import_modules_appwrite
description: Script pour importer modules CSV dans Appwrite
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  appwrite: ^11.0.0
  csv: ^5.0.0
  dart_appwrite: ^18.1.0
